use_frameworks!

target 'ZTuple_iOS_Tests' do
  pod 'EasyTuple', :path => '../'
  
  pod 'Specta', '~> 1.0'
  pod 'Expecta', '~> 1.0'
  pod 'OCMockito', '~> 5.0'
end

target 'ZTuple_macOS_Tests' do
  pod 'EasyTuple', :path => '../'
    
  pod 'Specta', '~> 1.0'
  pod 'Expecta', '~> 1.0'
  pod 'OCMockito', '~> 5.0'
end
