use_frameworks!

target 'EasyTuple_iOS' do
  platform :ios, '8.0'
  pod 'EasyTuple', :path => '../'
  
  target 'EasyTuple_iOS_Tests' do
    inherit! :search_paths
    pod 'Specta', '~> 1.0'
    pod 'Expecta', '~> 1.0'
    pod 'OCMockito', '~> 5.0'
  end
end

target 'EasyTuple_macOS' do
  platform :osx, '10.12'
  pod 'EasyTuple', :path => '../'
    
  target 'EasyTuple_macOS_Tests' do
    inherit! :search_paths
    pod 'Specta', '~> 1.0'
    pod 'Expecta', '~> 1.0'
    pod 'OCMockito', '~> 5.0'
  end
end
